/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package brutalchess.ui;

import brutalchess.BrutalChess;
/**
 *
 * @author Canes
 */
public class MenuPanel extends javax.swing.JPanel {

	/**
	 * Creates new form MenuPanel
	 */
	public MenuPanel() {
		initComponents();
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butSingle = new javax.swing.JButton();
        butExit = new javax.swing.JButton();
        butMulti = new javax.swing.JButton();
        butOnline = new javax.swing.JButton();

        butSingle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butSingle.setText("Single player");
        butSingle.setMaximumSize(new java.awt.Dimension(133, 31));
        butSingle.setMinimumSize(new java.awt.Dimension(133, 31));
        butSingle.setPreferredSize(new java.awt.Dimension(133, 31));
        butSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSingleActionPerformed(evt);
            }
        });

        butExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butExit.setText("Exit");
        butExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExitActionPerformed(evt);
            }
        });

        butMulti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butMulti.setText("Multiplayer");
        butMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMultiActionPerformed(evt);
            }
        });

        butOnline.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butOnline.setText("Online game");
        butOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOnlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(butExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butOnline, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(butMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butSingle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(butSingle, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butMulti, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butOnline, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butExit, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSingleActionPerformed
        BrutalChess.initDesk();
    }//GEN-LAST:event_butSingleActionPerformed

    private void butExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butExitActionPerformed

    private void butOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOnlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butOnlineActionPerformed

    private void butMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butMultiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butExit;
    private javax.swing.JButton butMulti;
    private javax.swing.JButton butOnline;
    private javax.swing.JButton butSingle;
    // End of variables declaration//GEN-END:variables
}
