/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package brutalchess.ui;

import static brutalchess.Const.*;
import brutalchess.BrutalChess;
import brutalchess.basis.Game;
import brutalchess.online.Server;
import javax.swing.JOptionPane;
/**
 *
 * @author Canes
 */
public class MenuPanel extends javax.swing.JPanel {

	/**
	 * Creates new form MenuPanel
	 */
	public MenuPanel() {
		initComponents();
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butLocal = new javax.swing.JButton();
        butExit = new javax.swing.JButton();
        butHost = new javax.swing.JButton();
        butClient = new javax.swing.JButton();

        butLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butLocal.setText("Local game");
        butLocal.setMaximumSize(new java.awt.Dimension(133, 31));
        butLocal.setMinimumSize(new java.awt.Dimension(133, 31));
        butLocal.setPreferredSize(new java.awt.Dimension(133, 31));
        butLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLocalActionPerformed(evt);
            }
        });

        butExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butExit.setText("Exit");
        butExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExitActionPerformed(evt);
            }
        });

        butHost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butHost.setText("Host game");
        butHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHostActionPerformed(evt);
            }
        });

        butClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butClient.setText("Connect to host");
        butClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(butExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butClient, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(butHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(butLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butHost, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butClient, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butExit, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLocalActionPerformed
        BrutalChess.initLocal();
    }//GEN-LAST:event_butLocalActionPerformed

    private void butExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butExitActionPerformed

    private void butClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClientActionPerformed
		String response;
		if (DEBUG){
			response = "127.0.0.1:42345";
		} else {
			response = JOptionPane.showInputDialog(null, "Write addresss and port of a host (127.0.0.1:1234)");
		}
		
		if (response != null){
			dbg("input: " + response);
			BrutalChess.initClient(response);
		}
    }//GEN-LAST:event_butClientActionPerformed

    private void butHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHostActionPerformed
		String response;
		int color;
		if (DEBUG){
			response = "42345";
			color = BLACK;
		} else {
			response = JOptionPane.showInputDialog(null, "What port should I listen to?");
			String[] options = {"WHITE", "BLACK"};
			color = JOptionPane.showOptionDialog(
					null,
					"What color do you want?",
					null,
					JOptionPane.DEFAULT_OPTION,
					JOptionPane.PLAIN_MESSAGE,
					null,
					options,
					null
			) == 0 ? WHITE : BLACK;
		}
		if (response != null){
			dbg("port: " + response);
			BrutalChess.initHost(response, color);
		}
    }//GEN-LAST:event_butHostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butClient;
    private javax.swing.JButton butExit;
    private javax.swing.JButton butHost;
    private javax.swing.JButton butLocal;
    // End of variables declaration//GEN-END:variables
}
